version: "0.2"
language: "en,pl"
dictionaries:
  - en_US
  - pl_PL
ignorePaths:
  - ".git/**"
  - "*.min.js"
  - "*.min.css"
  - "public/**"
  - "resources/**"
  - "node_modules/**"
  - "themes/PaperMod/**/*"
  - "config/_default/config.yaml"
words:
  - Ma≈Çachowski
  - kacpermalachowski
  - github
  - linkedin
  - stackoverflow
  - TVDG
  - Pozdro
